image: markhobson/maven-firefox
image1: markhobson/maven-chrome:jdk-11

stages:
  - build
  - smoke check


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

smoke:
  stage1: smoke check
  script:
    - mvn test -Dsuite=smoke -Denvironment=qa

  stage2: regression check
  script1:
    - mvn test -Dsuite=regression -Denvironment=qa

