name: CI Pipeline

on:
  push:
    branches: [ '*']
  pull_request:
    branches: [ '*']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3-eclipse-temurin-17
    services:
      selenium:
        image: selenium/standalone-chrome:102.0.5005.115-chromedriver-102.0.5005.61-grid-4.41.0-20260222
        ports:
          - 4444:4444
        options: >
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true compile

  smokesuite:
    runs-on: ubuntu-latest
    container:
      image: maven:3-eclipse-temurin-17
    needs: build
    services:
      selenium:
        image: selenium/standalone-chrome:102.0.5005.115-chromedriver-102.0.5005.61-grid-4.41.0-20260222
        ports:
          - 4444:4444
        options: >
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run smoke suite (qa)
        run: mvn --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true test -Dsuite=smoke -Denvironment=qa

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: smoke-reports
          path: |
            target/surefire-reports/index.html
            src/test/resources/PageScreenShots

  regressionsuite:
    runs-on: ubuntu-latest
    container:
      image: maven:3-eclipse-temurin-17
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run regression suite (qa)
        run: mvn --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true test -Dsuite=regression -Denvironment=qa

      - name: Upload regression report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: regression-reports
          path: |
            target/surefire-reports/index.html
            src/test/resources/PageScreenShots
